# .github/workflows/ci.yml

on:
 push:
    branches: 
      - main
 pull_request: 
    branches:
      - main

jobs: 
 build_apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy logiciel
        env:
          deploy_url: https://api.render.com/deploy/srv-${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{}' "$deploy_url"
