# .github/workflows/ci.yml

on:
 push:
    branches: [main]
 pull_request:
    branches: [main]

jobs: 
 build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy logiciel
        env: 
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
         curl -v "$deploy_url"

